name: Validation

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  test_and_lint:
    name: Run lint and tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install project
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run linting
        run: npm run eslint
  coverage_check:
    name: CoverageCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name:  Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup project
        run: npm ci && npm run publish-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,Node
          fail_ci_if_error: true
          files: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./codecov_report.txt
          verbose: true